### ISSUE TITLE
Wrong syntax parenthesis at multislot on template

### ISSUE THREAD

**Issue by ismtabo** [Chosko/language-clips#1]
Wrong syntax color closing parenthesis, when multisot is defined.

![error-parenthesis-clips](https://cloud.githubusercontent.com/assets/9568287/12177688/c272b6fa-b56d-11e5-8647-a2068a55c179.PNG)

**Comment by Chosko** [comment]
Thanks for the issue. I'll fix it tomorrow.

**Comment by Chosko** [comment]
Done and published
